version: "3.1"
nlu:
- intent: conferma
  examples: |
    - si
- intent: negazione
  examples: |
    - no, non mi serve
    - no
- intent: saluto
  examples: |
    - salve
    - ciao
    - buonasera
    - buongiorno
- intent: inform_formati
  examples: |
    - [1 2 3](formati)
    - [2 3 1](formati)
    - [2 3](formati)
    - [3 2 1](formati)
    - i formati sono (formati)
    - [4 3 2 1](formati)
- intent: stop_form
  examples: |
    - basta  non voglio continuare!
    - non mi serve
    - non voglio più dare informazione
    - mi sono stufato di rispondere
    - voglio andare avanti!
    - mi sono stufata di rispondere
    - fermati
- intent: creazione_corso
  examples: |
    - voglio creare un corso
    - voglio creare un corso didattico
    - vorrei creare un corso
    - vorrei creare un corso didattico
    - mi suggerisresti un corso?
    - fare un corso
    - mi serivrebbe creare un corso didattico
- intent: inform_nome_corso
  examples: |
    - [Introduzione al coding](nome_corso)
    - [Introduzione alla programmazione](nome_corso)
    - [Cicli for e while](nome_corso)
    - [Coding](nome_corso)
    - [Coding - livello avanzato](nome_corso)
    - [Uso delle sequenze](nome_corso)
    - [Funzioni e coding](nome_corso)
    - Il nome del corso sarà [Introduzione al coding](nome_corso)
    - [Introduzione al machine learning](nome_corso)
- intent: inform
  examples: |
    - [5](numero_lezioni)
    - [le abilità richieste del corso sono](abilità)
    - [tedesco](lingua)
    - [sette](età) anni
    - [quindici](numero_lezioni) lezioni
    - [30](numero_lezioni) lezioni
    - [20](numero_lezioni)
    - [sei](età) anni
    - [8](età)
    - [venti](numero_lezioni) lezioni
    - [dieci](numero_lezioni) lezioni
    - [cinese](lingua)
    - [3](numero_lezioni) lezioni
    - [francese](lingua)
    - [11](età) anni
    - [otto](età) anni
    - [2](numero_lezioni)
    - [sapere usare il for sapere usare il while](competenze)
    - [italiano](lingua)
    - [11](età)
    - [cinque](numero_lezioni) lezioni
    - [cicli for cicli whil sequenze](argomenti)
    - [dieci](età) anni
    - [25](numero_lezioni) lezioni
    - [7](età) anni
    - [undici](età) anni
    - [de](lingua)
    - [10](numero_lezioni)
    - [5](numero_lezioni) lezioni
    - [8](numero_lezioni) lezioni
    - [giapponese](lingua)
    - [gli argomenti del corso sono](argomenti)
    - [6](numero_lezioni) lezioni
    - [9](età)
    - [6](età) anni
    - [8](età) anni
    - [ita](lingua)
    - [saper usare le sequenze sapere le basi del coding](abilità)
    - [10](età) anni
    - [arabo](lingua)
    - [7](età)
    - [trenta](numero_lezioni) lezioni
    - [inglese](lingua)
    - [4](numero_lezioni) lezioni
    - [spagnolo](lingua)
    - [gli competenze finali del corso sono](competenze)
    - [fra](lingua)
    - [portogese](lingua)
