version: "3.1"
nlu:
- intent: conferma
  examples: |
    - si
- intent: negazione
  examples: |
    - no grazie
    - no, non mi serve
- intent: saluto
  examples: |
    - salve
    - ciao
    - buonasera
    - hey
- intent: inform_durata_lezioni
  examples: |
    - 30-60
    - 90 - 120
    - 0-30
    - 120
- intent: inform_metadato_da_modificare
  examples: |
    - durata_lezioni
    - abilità
    - lingua
    - età
    - competenze
    - nome_corso
    - numero_lezioni
- intent: stop_form
  examples: |
    - voglio andare avanti!
    - non mi serve
    - mi sono stufata di rispondere
    - non voglio più dare informazione
    - basta  non voglio continuare!
    - mi sono stufato di rispondere
- intent: creazione_corso
  examples: |
    - vorrei fare un corso
    - mi serivrebbe creare un corso didattico
    - vorrei creare un corso
    - fare un corso
    - voglio produrre un corso
    - mi suggerisresti un corso?
    - voglio creare un corso didattico
    - voglio creare un corso
- intent: inform_lingua
  examples: |
    - cinese
    - italiano
    - portogese
    - inglese
    - giapponese
    - francese
    - tedesco
- intent: inform_abilità
  examples: |
    - consocere le variabili
    - conoscere il concetto di iterazione
    - conoscere le basi di logica
    - conoscere le basi di matematica
    - conoscere le basi del coding, conoscere i cicli, conoscere le seqenze, conoscere le variabili
    - conoscere i cicli
    - conoscere le basi del coding
    - consocere il concetto di condizionale
- intent: inform_argomenti
  examples: |
    - if...else, sequenze
    - funzioni
    - condizionali
    - sequenze, funzioni, cicli
    - cicli
    - sequenze
    - cicli for, cicli while , cicli annidati
    - variabili
    - variabili, cicli
- intent: inform_competenze
  examples: |
    - conoscere i cicli while
    - conoscere if...else
    - conoscere le basi del coding, conoscere i cicli, conoscere le sequenze
    - saper utilizzare i condizionali e le variabili
    - saper implementare i cicli
    - conoscere le seqenze, conoscere i cicli
    - saper utilizzare le variabili
    - conoscere i condizionali
    - saper padroneggiare i cicli for
- intent: inform_età
  examples: |
    - 9
    - 8 anni
    - 7 anni
    - 10 anni
    - 6
    - 11
    - 7
    - 8
    - 9 anni
    - 12
    - 6 anni
- intent: inform_tempo
  examples: |
    - 15 min
    - 20 minuti
    - 15 minuti
    - 25 minuti
    - 30
    - 20 min
    - 10 min
    - 10
    - 30 min
    - 25
    - 10 minuti
    - 30 minuti
- intent: inform_nome_corso
  examples: |
    - Introduzione alla programmazione
    - Cicli for
    - Funzioni
    - Coding - livello avanzato
    - Cicli for e while
    - Coding - livello medio
    - Corso base di coding
    - Cicli annidati
    - Coding - livello base
    - Cicli while
    - Coding
    - Introduzione al coding
    - I condizionali
    - Uso delle sequenze
    - Corso intermedio di coding
    - Corso avanzato di coding
- intent: inform_formati
  examples: |
    - 3
    - 2 4
    - 1 2 3 4
    - 2 3
    - 4 1 3
    - 2
    - 1 2
    - 2 1 3 4
    - 3 2
    - 3 1
    - 4 3 2 1
    - 1 4
    - 1
    - 
    - 4
    - 4 3
    - 1 3
    - 1 2 3
    - 3 2 1 4
- intent: inform_numero_lezioni
  examples: |
    - 5
    - 25 lezioni
    - 30
    - 70 lezioni
    - 20
    - 20 lezioni
    - 30 lezioni
    - 25
    - 40
    - 55
    - 10 lezioni
    - 35 lezioni
    - 50 lezioni
    - 60 lezioni
    - 65
    - 70
    - 35
    - 45
    - 40 lezioni
    - 5 lezioni
    - 55 lezioni
- intent: inform_videolezioni
  examples: |
    - 2 1 4 5
    - 5
    - 3 1
    - 2 1 3 4 5
    - 1 2 3 5
    - 3 4 1
    - 4 2
    - 1 2 5
    - 5 3
    - 1
    - 1 3
    - 3 2 1
    - 1 4 2
    - 3 4
    - 1 5
    - 1 2
    - 2 3 1
    - 2 1
    - 4 5
    - 3 1 4
    - 3
    - 4
    - 2 4 5
- intent: inform_esercizi
  examples: |
    - 1 2
    - 3
    - 3 2 5
    - 1 2 5
    - 4 2
    - 2 1 4 5
    - 3 4
    - 3 2 1
    - 3 4 1
    - 1 5
    - 1 3 4
    - 4 5 3 2 1
    - 1 3
    - 4 5
    - 5
    - 5 3 2 1 4
    - 2
    - 1 2 3 5
    - 5 3
    - 1
    - 2 1 3 4 5
    - 3 1 4
    - 2 3 1
- intent: inform_quiz
  examples: |
    - 4 2
    - 5 3 2 1 4
    - 4 5
    - 3 1 4
    - 4
    - 1 5
    - 1 3
    - 1 4 2
    - 5
    - 2 1
    - 2 1 3 4 5
    - 2 4 5
    - 1 2
    - 3 2 1
    - 1 2 3 4 5
    - 2 1 4 5
    - 3 2 5
    - 4 5 3 2 1
    - 1 3 4
    - 5 3
    - 1 2 5
    - 3
    - 1 2 3 5
- intent: inform_documenti
  examples: |
    - 5 3 2 1 4
    - 2 3 1
    - 3 4 1
    - 2 1 4 5
    - 3 2 1
    - 3 2 5
    - 1 2 3 5
    - 4
    - 3 1
    - 4 5 3 2 1
    - 1 2
    - 1 5
    - 2 1 3 4 5
    - 5 3
    - 1 3
    - 1 2 5
    - 5
    - 3
    - 3 1 4
    - 2
    - 1 3 4
    - 1
    - 2 1
- intent: inform_cambio_metadato
  examples: |
    - 10
    - 55 lezioni
    - Corso avanzato di coding
    - 30
    - Introduzione alla programmazione
    - condizionali, cicli
    - conoscere le basi di matematica
    - 40 lezioni
    - conoscere i condizionali
    - consocere il concetto di condizionale
    - 6
    - conoscere le basi del coding, conoscere i cicli, conoscere le sequenze
    - 30-60
    - 5 lezioni
    - 50 lezioni
    - 40
    - cicli for, cicli while , cicli annidati
    - Cicli for e while
    - Coding
    - Coding - livello medio
    - conoscere le basi del coding, conoscere i cicli, conoscere le seqenze, conoscere le variabili
    - consocere le variabili
    - conoscere le seqenze
    - consocere il concetto di iterazione
    - Introduzione al coding
    - 20 lezioni
    - 45 lezioni
    - 60 lezioni
    - 8
    - saper utilizzare le variabili
    - saper padroneggiare i cicli e le sequenze
    - 120
    - Introduzone ai cicli
    - 50
    - 10 lezioni
    - Coding - livello avanzato
    - if...else, sequenze
    - sequenze, funzioni, cicli
    - consocere le sequenze
    - condizionali
    - saper utilizzare i condizionali e le variabili
    - cicli
    - 65 lezioni
    - funzioni
    - Cicli for
    - conoscere i cicli while
    - 9 anni
    - 25 lezioni
    - If...else
    - 8 anni
    - variabili, cicli
    - I condizionali
    - 20
    - conoscere le basi del coding
    - conoscere le basi di logica
    - 35 lezioni
    - variabili
    - Corso intermedio di coding
    - inglese
    - italiano
    - Sequenze
    - saper implementare i cicli
    - 70 lezioni
    - 7
    - saper utilizzare i condizionali
    - 10 anni
    - 11
    - Coding - livello base
    - conoscere le seqenze, conoscere i cicli
    - 6 anni
    - saper padroneggiare i cicli for
    - Funzioni
